// src/components/layout/NavigationComponent.vue
<template>
  <nav
    ref="navRef"
    :class="[
      styles.nav,
      isScrolled ? styles.scrolled : styles.notScrolled,
      'transition-all duration-300'
    ]"
  >
    <div :class="styles.container">
      <div :class="styles.inner">
        <!-- Logo -->
        <div :class="styles.logoButton" @click="() => scrollToSection('hero')">
          <div :class="styles.logoIconWrapper">
            <Code :class="styles.logoIcon" />
          </div>
          <span :class="styles.logoText">FusionCode</span>
        </div>

        <!-- Desktop Navigation -->
        <div :class="styles.desktopNav">
          <button
            v-for="{ id, label } in navItems"
            :key="id"
            @click="() => scrollToSection(id)"
            :class="[
              styles.navButton,
              activeSection === id ? styles.navButtonActive : styles.navButtonInactive
            ]"
          >
            {{ label }}
          </button>
        </div>

        <!-- Mobile Menu Toggle -->
        <div :class="styles.menuToggleWrapper">
          <button :class="styles.menuToggle" @click="toggleMenu">
            <X v-if="isOpen" :size="20" />
            <Menu v-else :size="20" />
          </button>
        </div>
      </div>

      <!-- Mobile Navigation -->
      <div
        v-if="isOpen || isAnimatingOut"
        :class="[
          styles.mobileNav,
          isAnimatingOut ? styles.mobileNavLeave : styles.mobileNavEnter
        ]"
      >
        <div :class="styles.mobileNavContent">
          <button
            v-for="{ id, label } in navItems"
            :key="id"
            @click="() => scrollToSection(id)"
            :class="[
              styles.mobileNavItem,
              activeSection === id ? styles.navButtonActive : styles.navButtonInactive
            ]"
          >
            {{ label }}
          </button>
        </div>
      </div>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, nextTick } from 'vue'
import { useEventListener } from '@vueuse/core'
import { Menu, X, Code } from 'lucide-vue-next'
import styles from './Navigation.module.css'

// Navigation items
const navItems = [
  { id: 'hero', label: 'Home' },
  { id: 'about', label: 'About' },
  { id: 'experience', label: 'Experience' },
  { id: 'projects', label: 'Projects' },
  { id: 'skills', label: 'Skills' },
  { id: 'strengths', label: 'Strengths' },
  { id: 'education', label: 'Education' },
  { id: 'contact', label: 'Contact' },
]

// Reactive state
const isOpen = ref(false)
const isAnimatingOut = ref(false)
const activeSection = ref('hero')
const isScrolled = ref(false)
const navRef = ref<HTMLElement | null>(null)

// Sync navigation height with CSS variable
const syncHeight = () => {
  if (navRef.value) {
    document.documentElement.style.setProperty(
      '--nav-height',
      `${navRef.value.offsetHeight}px`
    )
  }
}

// Handle scroll background
useEventListener('scroll', () => {
  isScrolled.value = window.scrollY > 50
}, { passive: true })

// Calculate active section (scroll spy)
const calcActiveSection = () => {
  const headH = navRef.value?.offsetHeight ?? 0
  let currentId = navItems[0].id

  for (const { id } of navItems) {
    const el = document.getElementById(id)
    if (!el) continue

    const offset = el.getBoundingClientRect().top - headH
    if (offset <= 0) {
      currentId = id
    } else {
      break
    }
  }

  activeSection.value = currentId
}

// Scroll spy with RAF throttling
let ticking = false
useEventListener('scroll', () => {
  if (!ticking) {
    window.requestAnimationFrame(() => {
      calcActiveSection()
      ticking = false
    })
    ticking = true
  }
}, { passive: true })

useEventListener('resize', () => {
  syncHeight()
  calcActiveSection()
})

// Close mobile menu with animation
const closeMobileMenu = () => {
  if (isOpen.value) {
    isAnimatingOut.value = true
    setTimeout(() => {
      isOpen.value = false
      isAnimatingOut.value = false
    }, 250)
  }
}

// Smooth scroll to section
const scrollToSection = (id: string) => {
  const el = document.getElementById(id)
  if (el) {
    const headH = navRef.value?.offsetHeight ?? 0
    const target = Math.min(
      el.getBoundingClientRect().top + window.pageYOffset - headH,
      document.body.scrollHeight - window.innerHeight
    )

    window.scrollTo({ top: target, behavior: 'smooth' })
    activeSection.value = id // Immediately highlight the section
  }
  closeMobileMenu()
}

// Toggle mobile menu
const toggleMenu = () => {
  if (isOpen.value) {
    isAnimatingOut.value = true
    setTimeout(() => {
      isOpen.value = false
      isAnimatingOut.value = false
    }, 250)
  } else {
    isOpen.value = true
  }
}

onMounted(async () => {
  await nextTick()
  syncHeight()
  calcActiveSection()
})
</script>

// src/components/layout/Navigation.tsx
import React, { useState, useEffect, useRef } from 'react';
import { Menu, X, Code } from 'lucide-react';
import styles from './Navigation.module.css';

/* --- menu items list --- */
const navItems = [
  { id: 'hero',        label: 'Home' },
  { id: 'about',       label: 'About' },
  { id: 'experience',  label: 'Experience' },
  { id: 'projects',    label: 'Projects' },
  { id: 'skills',      label: 'Skills' },
  { id: 'strengths',   label: 'Strengths' },
  { id: 'education',   label: 'Education' },
  { id: 'contact',     label: 'Contact' },
];

export const Navigation = () => {
  /* --- state --- */
  const [isOpen, setIsOpen]               = useState(false);
  const [isAnimatingOut, setIsAnimatingOut] = useState(false);
  const [activeSection, setActiveSection] = useState('hero');
  const [isScrolled, setIsScrolled]       = useState(false);
  const navRef = useRef<HTMLElement | null>(null);

  /* -------------------------------------------------------------------- */
  /*    1. synchronize actual navbar height with CSS variable              */
  /* -------------------------------------------------------------------- */
  useEffect(() => {
    const syncHeight = () => {
      if (navRef.current) {
        const h = navRef.current.offsetHeight;
        document.documentElement.style.setProperty('--nav-height', `${h}px`);
      }
    };
    syncHeight();
    window.addEventListener('resize', syncHeight);
    return () => window.removeEventListener('resize', syncHeight);
  }, []);

  /* -------------------------------------------------------------------- */
  /*    2. change navbar background on scroll                              */
  /* -------------------------------------------------------------------- */
  useEffect(() => {
    const onScroll = () => setIsScrolled(window.scrollY > 50);
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  /* -------------------------------------------------------------------- */
  /*    3. determine active section using IntersectionObserver             */
  /* -------------------------------------------------------------------- */
  useEffect(() => {
    if (!('IntersectionObserver' in window)) return;

    const navHeight = navRef.current?.offsetHeight ?? 0;
    const observer  = new IntersectionObserver(
      entries => {
        entries.forEach(entry => {
          if (entry.isIntersecting) {
            setActiveSection((entry.target as HTMLElement).id);
          }
        });
      },
      {
        rootMargin: `-${navHeight}px 0px 0px 0px`, // accounting for header height
        threshold : 0.6,                           // 60% of block visible → active
      }
    );

    navItems.forEach(item => {
      const el = document.getElementById(item.id);
      if (el) observer.observe(el);
    });

    return () => observer.disconnect();
  }, []);

  /* -------------------------------------------------------------------- */
  /*    4. helper functions                                                */
  /* -------------------------------------------------------------------- */
  /** Closes mobile menu with a short animation */
  const closeMobileMenu = () => {
    if (isOpen) {
      setIsAnimatingOut(true);
      setTimeout(() => {
        setIsOpen(false);
        setIsAnimatingOut(false);
      }, 250);
    }
  };

  /** Smoothly scrolls to section with adjustment for actual navbar height */
  const scrollToSection = (id: string) => {
    const el = document.getElementById(id);
    if (el) {
      const navH   = navRef.current?.offsetHeight ?? 0;
      const target = Math.min(
        el.getBoundingClientRect().top + window.pageYOffset - navH,
        document.body.scrollHeight - window.innerHeight
      );
      window.scrollTo({ top: target, behavior: 'smooth' });
    }
    closeMobileMenu();
  };

  /** Opens/closes burger menu */
  const toggleMenu = () => {
    if (isOpen) {
      setIsAnimatingOut(true);
      setTimeout(() => {
        setIsOpen(false);
        setIsAnimatingOut(false);
      }, 250);
    } else {
      setIsOpen(true);
    }
  };

  /* -------------------------------------------------------------------- */
  /*    5. markup                                                         */
  /* -------------------------------------------------------------------- */
  return (
    <nav
      ref={navRef}
      className={`${styles.nav} ${isScrolled ? styles.scrolled : styles.notScrolled} transition-all duration-300`}
    >
      <div className={styles.container}>
        <div className={styles.inner}>
          {/* Logo */}
          <div className={styles.logoButton} onClick={() => scrollToSection('hero')}>
            <div className={styles.logoIconWrapper}>
              <Code className="h-5 w-5 text-blue-300" />
            </div>
            <span className={styles.logoText}>FusionCode</span>
          </div>

          {/* Desktop menu */}
          <div className={styles.desktopNav}>
            {navItems.map(item => (
              <button
                key={item.id}
                onClick={() => scrollToSection(item.id)}
                className={`${styles.navButton} ${
                  activeSection === item.id ? styles.navButtonActive : styles.navButtonInactive
                }`}
              >
                {item.label}
              </button>
            ))}
          </div>

          {/* Burger menu button */}
          <div className={styles.menuToggleWrapper}>
            <button className={styles.menuToggle} onClick={toggleMenu}>
              {isOpen ? <X size={20} /> : <Menu size={20} />}
            </button>
          </div>
        </div>

        {/* Mobile menu */}
        {(isOpen || isAnimatingOut) && (
          <div
            className={`${styles.mobileNav} ${
              isAnimatingOut ? styles.mobileNavLeave : styles.mobileNavEnter
            }`}
          >
            <div className={styles.mobileNavContent}>
              {navItems.map(item => (
                <button
                  key={item.id}
                  onClick={() => scrollToSection(item.id)}
                  className={`${styles.mobileNavItem} ${
                    activeSection === item.id ? styles.navButtonActive : styles.navButtonInactive
                  }`}
                >
                  {item.label}
                </button>
              ))}
            </div>
          </div>
        )}
      </div>
    </nav>
  );
};
