// src/views/NotFound.vue
<template>
  <div :class="styles.container">
    <!-- Background elements -->
    <div :class="styles.backgroundElement1"></div>
    <div :class="styles.backgroundElement2"></div>
    
    <div :class="styles.content">
      <!-- 404 Number -->
      <div :class="styles.numberContainer">
        <h1 :class="styles.number">
          404
        </h1>
        <div :class="styles.divider"></div>
      </div>

      <!-- Error message -->
      <div :class="styles.textContent">
        <h2 :class="styles.title">
          Page Not Found
        </h2>
        <p :class="styles.description">
          The page you're looking for doesn't exist or has been moved.
        </p>
      </div>

      <!-- Action buttons -->
      <div :class="styles.buttonContainer">
        <RouterLink 
          to="/" 
          :class="styles.primaryButton"
        >
          <Home :class="styles.buttonIcon" />
          Go Home
        </RouterLink>
        <button 
          @click="goBack"
          :class="styles.secondaryButton"
        >
          <ArrowLeft :class="styles.buttonIcon" />
          Go Back
        </button>
      </div>

      <!-- Decorative elements -->
      <div :class="styles.dotsContainer">
        <div :class="styles.dot"></div>
        <div :class="styles.dot"></div>
        <div :class="styles.dot"></div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue'
import { useRoute, RouterLink } from 'vue-router'
import { Home, ArrowLeft } from 'lucide-vue-next'
import styles from './NotFound.module.css'

const route = useRoute()

const goBack = () => {
  window.history.back()
}

onMounted(() => {
  // Only log in development
  if (import.meta.env.DEV) {
    console.error(
      "404 Error: User attempted to access non-existent route:",
      route.path
    )
  }
})
</script>

// src/pages/NotFound.tsx
import { useLocation } from "react-router-dom";
import { useEffect } from "react";
import { Home, ArrowLeft } from "lucide-react";

const NotFound = () => {
  const location = useLocation();

  useEffect(() => {
    // Only log in development
    if (process.env.NODE_ENV === 'development') {
      console.error(
        "404 Error: User attempted to access non-existent route:",
        location.pathname
      );
    }
  }, [location.pathname]);

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-slate-900 via-gray-900/50 to-slate-900 relative overflow-hidden">
      {/* Background elements */}
      <div className="absolute top-0 left-1/4 w-96 h-96 bg-blue-500/5 rounded-full blur-3xl"></div>
      <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-purple-500/5 rounded-full blur-3xl"></div>
      
      <div className="text-center relative z-10 max-w-md mx-auto px-4">
        {/* 404 Number */}
        <div className="mb-8">
          <h1 className="text-8xl md:text-9xl font-bold bg-gradient-to-r from-blue-400 via-purple-400 to-pink-400 bg-clip-text text-transparent mb-4">
            404
          </h1>
          <div className="w-24 h-1 bg-gradient-to-r from-blue-400 to-purple-400 rounded-full mx-auto"></div>
        </div>

        {/* Error message */}
        <div className="mb-12">
          <h2 className="text-2xl md:text-3xl font-bold text-white mb-4">
            Page Not Found
          </h2>
          <p className="text-gray-400 text-lg leading-relaxed">
            The page you're looking for doesn't exist or has been moved.
          </p>
        </div>

        {/* Action buttons */}
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <a 
            href="/" 
            className="inline-flex items-center justify-center px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg transition-all duration-300 hover:scale-105 shadow-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-400/50 focus-visible:ring-offset-0"
          >
            <Home className="mr-2 h-5 w-5" />
            Go Home
          </a>
          <button 
            onClick={() => window.history.back()}
            className="inline-flex items-center justify-center px-6 py-3 border-2 border-gray-400 text-gray-300 hover:bg-gray-800 hover:text-white font-semibold rounded-lg transition-all duration-300 hover:scale-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gray-400/50 focus-visible:ring-offset-0"
          >
            <ArrowLeft className="mr-2 h-5 w-5" />
            Go Back
          </button>
        </div>

        {/* Decorative elements */}
        <div className="mt-16 flex justify-center space-x-2">
          <div className="w-2 h-2 bg-blue-400 rounded-full animate-pulse"></div>
          <div className="w-2 h-2 bg-purple-400 rounded-full animate-pulse [animation-delay:0.2s]"></div>
          <div className="w-2 h-2 bg-pink-400 rounded-full animate-pulse [animation-delay:0.4s]"></div>
        </div>
      </div>
    </div>
  );
};

export default NotFound;
